# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 920cc5d1497f202120d268b223020c15a4e3682ecc255a36335933b3a208fe0eb47558c5c3add8d3b44a20137f12879c2698f93092e74d91537d630d106e3616

test:
  secret_key_base: e9251fc968b5192f7f5f59d4709349f50b9eabe1c13889dfe228bd2af2822755d5d706b4d1a933550ff4c1516174db73a6900b94583557f14bf34945c974dc16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
